server:
  port: 8090
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    product-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/v1/**
    app-server:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/v1/**